// COUNTRIES
export const SET_SELECTED_AUTOCOMPLETE_COUNTRY = 'SET_SELECTED_AUTOCOMPLETE_COUNTRY'

// NEWS
export const FETCH_NEWS_START   = 'FETCH_NEWS_START'
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS'
export const FETCH_NEWS_FAIL    = 'FETCH_NEWS_FAIL'